# Generated by Django 5.1.1 on 2024-09-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('button_text', models.CharField(max_length=100)),
            ],
        ),
    ]
